### ISSUE TITLE
Add travis-notification via gitter

### ISSUE THREAD

**Issue by serious6** [OfficeDev/ews-java-api#134]
Hi since we are having gitter integration we should think about beeing notified on broken and successful builds. A good place could be the ews-java-api gitter chat where everyone get´s informed about the status after the build started. For this reason the _.tavis.yml_ could be updated with the following configuration:

```
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/<add webhook id here>
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
```

What do you think of this?
